name: svarah
description: Svarah - AAC Communication Helper App

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_tts: ^4.2.3
  image_picker: ^1.1.2
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0
  vibration: ^3.1.0
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  archive: ^3.4.10
  share_plus: ^7.2.2
  flutter_sound: ^9.2.13
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_crashlytics: ^5.0.0
  firebase_performance: ^0.11.0
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  in_app_purchase: ^3.1.13  # Google Play Billing for subscriptions
  url_launcher: ^6.2.5  # For opening legal documents in browser

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/symbols/
    # - assets/icons/     # Commented out - directory is empty
    # - assets/images/    # Commented out - directory is empty  
    # - assets/sounds/    # Commented out - directory is empty

  # Performance optimizations
  generate: true