name: aac_flutter_app
description: A Flutter application for Augmentative and Alternative Communication (AAC).

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/symbols/