name: aac_flutter_app
description: A Flutter application for Augmentative and Alternative Communication (AAC).

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_tts: ^4.2.3
  image_picker: ^1.1.2
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0
  vibration: ^1.8.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/symbols/
    - assets/icons/
    - assets/sounds/
    - assets/images/

