import '../models/symbol.dart';

class SampleData {
  static List<Category> getSampleCategories() {
    return [
      Category(
        name: 'Food & Drinks',
        iconPath: 'assets/icons/food.png',
        colorCode: 0xFFFF6B6B, // Red
      ),
      Category(
        name: 'Vehicles',
        iconPath: 'assets/icons/vehicles.png',
        colorCode: 0xFF4ECDC4, // Teal
      ),
      Category(
        name: 'Emotions',
        iconPath: 'assets/icons/emotions.png',
        colorCode: 0xFFFFE66D, // Yellow
      ),
      Category(
        name: 'Actions',
        iconPath: 'assets/icons/actions.png',
        colorCode: 0xFF6C63FF, // Purple
      ),
      Category(
        name: 'Family',
        iconPath: 'assets/icons/family.png',
        colorCode: 0xFFFF9F43, // Orange
      ),
      Category(
        name: 'Basic Needs',
        iconPath: 'assets/icons/needs.png',
        colorCode: 0xFF51CF66, // Green
      ),
    ];
  }

  static List<Symbol> getSampleSymbols() {
    return [
      // Food & Drinks - 50+ frequently used items
      // Basic foods
      Symbol(label: 'Apple', imagePath: 'assets/symbols/Apple.png', category: 'Food & Drinks', description: 'Red apple fruit'),
      Symbol(label: 'Water', imagePath: 'assets/symbols/Water.png', category: 'Food & Drinks', description: 'Glass of water'),
      Symbol(label: 'Milk', imagePath: 'emoji:🥛', category: 'Food & Drinks', description: 'Glass of milk'),
      Symbol(label: 'Bread', imagePath: 'emoji:🍞', category: 'Food & Drinks', description: 'Slice of bread'),
      Symbol(label: 'Banana', imagePath: 'emoji:🍌', category: 'Food & Drinks', description: 'Yellow banana'),
      Symbol(label: 'Orange', imagePath: 'emoji:🍊', category: 'Food & Drinks', description: 'Orange fruit'),
      Symbol(label: 'Grapes', imagePath: 'emoji:🍇', category: 'Food & Drinks', description: 'Purple grapes'),
      Symbol(label: 'Strawberry', imagePath: 'emoji:🍓', category: 'Food & Drinks', description: 'Red strawberry'),
      Symbol(label: 'Tomato', imagePath: 'emoji:🍅', category: 'Food & Drinks', description: 'Red tomato'),
      Symbol(label: 'Carrot', imagePath: 'emoji:🥕', category: 'Food & Drinks', description: 'Orange carrot'),
      
      // Meals and prepared foods
      Symbol(label: 'Breakfast', imagePath: 'emoji:🍳', category: 'Food & Drinks', description: 'Morning meal'),
      Symbol(label: 'Lunch', imagePath: 'emoji:🥙', category: 'Food & Drinks', description: 'Midday meal'),
      Symbol(label: 'Dinner', imagePath: 'emoji:🍽️', category: 'Food & Drinks', description: 'Evening meal'),
      Symbol(label: 'Snack', imagePath: 'emoji:🍿', category: 'Food & Drinks', description: 'Small food portion'),
      Symbol(label: 'Sandwich', imagePath: 'emoji:🥪', category: 'Food & Drinks', description: 'Bread with filling'),
      Symbol(label: 'Pizza', imagePath: 'emoji:🍕', category: 'Food & Drinks', description: 'Slice of pizza'),
      Symbol(label: 'Pasta', imagePath: 'emoji:🍝', category: 'Food & Drinks', description: 'Spaghetti noodles'),
      Symbol(label: 'Rice', imagePath: 'emoji:🍚', category: 'Food & Drinks', description: 'Cooked rice'),
      Symbol(label: 'Soup', imagePath: 'emoji:🍲', category: 'Food & Drinks', description: 'Hot soup'),
      Symbol(label: 'Salad', imagePath: 'emoji:🥗', category: 'Food & Drinks', description: 'Green salad'),
      
      // Snacks and treats
      Symbol(label: 'Cookie', imagePath: 'emoji:🍪', category: 'Food & Drinks', description: 'Chocolate chip cookie'),
      Symbol(label: 'Cake', imagePath: 'emoji:🍰', category: 'Food & Drinks', description: 'Birthday cake'),
      Symbol(label: 'Ice Cream', imagePath: 'emoji:🍦', category: 'Food & Drinks', description: 'Ice cream cone'),
      Symbol(label: 'Candy', imagePath: 'emoji:🍬', category: 'Food & Drinks', description: 'Sweet candy'),
      Symbol(label: 'Chocolate', imagePath: 'emoji:🍫', category: 'Food & Drinks', description: 'Chocolate bar'),
      Symbol(label: 'Donut', imagePath: 'emoji:🍩', category: 'Food & Drinks', description: 'Sweet donut'),
      Symbol(label: 'Popcorn', imagePath: 'emoji:🍿', category: 'Food & Drinks', description: 'Movie popcorn'),
      Symbol(label: 'Crackers', imagePath: 'emoji:🍘', category: 'Food & Drinks', description: 'Crispy crackers'),
      Symbol(label: 'Chips', imagePath: 'emoji:🥔', category: 'Food & Drinks', description: 'Potato chips'),
      Symbol(label: 'Pretzel', imagePath: 'emoji:🥨', category: 'Food & Drinks', description: 'Twisted pretzel'),
      
      // Drinks
      Symbol(label: 'Juice', imagePath: 'emoji:🧃', category: 'Food & Drinks', description: 'Fruit juice box'),
      Symbol(label: 'Coffee', imagePath: 'emoji:☕', category: 'Food & Drinks', description: 'Hot coffee'),
      Symbol(label: 'Tea', imagePath: 'emoji:🍵', category: 'Food & Drinks', description: 'Hot tea'),
      Symbol(label: 'Soda', imagePath: 'emoji:🥤', category: 'Food & Drinks', description: 'Carbonated drink'),
      Symbol(label: 'Smoothie', imagePath: 'emoji:🥤', category: 'Food & Drinks', description: 'Fruit smoothie'),
      Symbol(label: 'Hot Chocolate', imagePath: 'emoji:☕', category: 'Food & Drinks', description: 'Warm chocolate drink'),
      
      // Proteins
      Symbol(label: 'Chicken', imagePath: 'emoji:🍗', category: 'Food & Drinks', description: 'Chicken meat'),
      Symbol(label: 'Fish', imagePath: 'emoji:🐟', category: 'Food & Drinks', description: 'Fresh fish'),
      Symbol(label: 'Egg', imagePath: 'emoji:🥚', category: 'Food & Drinks', description: 'Chicken egg'),
      Symbol(label: 'Meat', imagePath: 'emoji:🥩', category: 'Food & Drinks', description: 'Red meat'),
      Symbol(label: 'Cheese', imagePath: 'emoji:🧀', category: 'Food & Drinks', description: 'Yellow cheese'),
      Symbol(label: 'Yogurt', imagePath: 'emoji:🥛', category: 'Food & Drinks', description: 'Creamy yogurt'),
      
      // More fruits and vegetables
      Symbol(label: 'Watermelon', imagePath: 'emoji:🍉', category: 'Food & Drinks', description: 'Green watermelon'),
      Symbol(label: 'Pineapple', imagePath: 'emoji:🍍', category: 'Food & Drinks', description: 'Yellow pineapple'),
      Symbol(label: 'Peach', imagePath: 'emoji:🍑', category: 'Food & Drinks', description: 'Fuzzy peach'),
      Symbol(label: 'Pear', imagePath: 'emoji:🍐', category: 'Food & Drinks', description: 'Green pear'),
      Symbol(label: 'Lemon', imagePath: 'emoji:🍋', category: 'Food & Drinks', description: 'Sour lemon'),
      Symbol(label: 'Broccoli', imagePath: 'emoji:🥦', category: 'Food & Drinks', description: 'Green broccoli'),
      Symbol(label: 'Corn', imagePath: 'emoji:🌽', category: 'Food & Drinks', description: 'Yellow corn'),
      Symbol(label: 'Potato', imagePath: 'emoji:🥔', category: 'Food & Drinks', description: 'Brown potato'),
      Symbol(label: 'Onion', imagePath: 'emoji:🧅', category: 'Food & Drinks', description: 'White onion'),
      Symbol(label: 'Lettuce', imagePath: 'emoji:🥬', category: 'Food & Drinks', description: 'Green lettuce'),

      // Vehicles - 50+ common transportation
      Symbol(label: 'Car', imagePath: 'assets/symbols/Car.png', category: 'Vehicles', description: 'Family car'),
      Symbol(label: 'Bus', imagePath: 'emoji:🚌', category: 'Vehicles', description: 'Public bus'),
      Symbol(label: 'Train', imagePath: 'emoji:🚂', category: 'Vehicles', description: 'Steam train'),
      Symbol(label: 'Airplane', imagePath: 'emoji:✈️', category: 'Vehicles', description: 'Flying airplane'),
      Symbol(label: 'Bicycle', imagePath: 'emoji:🚴', category: 'Vehicles', description: 'Two-wheel bike'),
      Symbol(label: 'Motorcycle', imagePath: 'emoji:🏍️', category: 'Vehicles', description: 'Fast motorcycle'),
      Symbol(label: 'Truck', imagePath: 'emoji:🚚', category: 'Vehicles', description: 'Delivery truck'),
      Symbol(label: 'Police Car', imagePath: 'emoji:🚓', category: 'Vehicles', description: 'Police vehicle'),
      Symbol(label: 'Fire Truck', imagePath: 'emoji:🚒', category: 'Vehicles', description: 'Emergency fire truck'),
      Symbol(label: 'Ambulance', imagePath: 'emoji:🚑', category: 'Vehicles', description: 'Medical ambulance'),
      Symbol(label: 'Taxi', imagePath: 'emoji:🚕', category: 'Vehicles', description: 'Yellow taxi'),
      Symbol(label: 'School Bus', imagePath: 'emoji:🚌', category: 'Vehicles', description: 'Yellow school bus'),
      Symbol(label: 'Subway', imagePath: 'emoji:🚇', category: 'Vehicles', description: 'Underground train'),
      Symbol(label: 'Tram', imagePath: 'emoji:🚊', category: 'Vehicles', description: 'City tram'),
      Symbol(label: 'Helicopter', imagePath: 'emoji:🚁', category: 'Vehicles', description: 'Flying helicopter'),
      Symbol(label: 'Boat', imagePath: 'emoji:⛵', category: 'Vehicles', description: 'Sailing boat'),
      Symbol(label: 'Ship', imagePath: 'emoji:🚢', category: 'Vehicles', description: 'Large ship'),
      Symbol(label: 'Scooter', imagePath: 'emoji:🛴', category: 'Vehicles', description: 'Kick scooter'),
      Symbol(label: 'Skateboard', imagePath: 'emoji:🛹', category: 'Vehicles', description: 'Four-wheel skateboard'),
      Symbol(label: 'Wheelchair', imagePath: 'emoji:♿', category: 'Vehicles', description: 'Mobility wheelchair'),
      Symbol(label: 'Rocket', imagePath: 'emoji:🚀', category: 'Vehicles', description: 'Space rocket'),
      Symbol(label: 'Hot Air Balloon', imagePath: 'emoji:🎈', category: 'Vehicles', description: 'Flying balloon'),
      Symbol(label: 'Parachute', imagePath: 'emoji:🪂', category: 'Vehicles', description: 'Safety parachute'),
      Symbol(label: 'Cable Car', imagePath: 'emoji:🚠', category: 'Vehicles', description: 'Mountain cable car'),
      Symbol(label: 'Monorail', imagePath: 'emoji:🚝', category: 'Vehicles', description: 'Single-track train'),
      Symbol(label: 'Trolley', imagePath: 'emoji:🚋', category: 'Vehicles', description: 'Electric trolley'),
      Symbol(label: 'Van', imagePath: 'emoji:🚐', category: 'Vehicles', description: 'Family van'),
      Symbol(label: 'SUV', imagePath: 'emoji:🚙', category: 'Vehicles', description: 'Sport utility vehicle'),
      Symbol(label: 'Pickup Truck', imagePath: 'emoji:🛻', category: 'Vehicles', description: 'Open-bed truck'),
      Symbol(label: 'Tractor', imagePath: 'emoji:🚜', category: 'Vehicles', description: 'Farm tractor'),
      Symbol(label: 'Bulldozer', imagePath: 'emoji:🚚', category: 'Vehicles', description: 'Construction bulldozer'),
      Symbol(label: 'Excavator', imagePath: 'emoji:🚚', category: 'Vehicles', description: 'Digging excavator'),
      Symbol(label: 'Cement Mixer', imagePath: 'emoji:🚚', category: 'Vehicles', description: 'Construction mixer'),
      Symbol(label: 'Garbage Truck', imagePath: 'emoji:🚚', category: 'Vehicles', description: 'Waste collection truck'),
      Symbol(label: 'Ice Cream Truck', imagePath: 'emoji:🚚', category: 'Vehicles', description: 'Mobile ice cream vendor'),
      Symbol(label: 'Mail Truck', imagePath: 'emoji:🚚', category: 'Vehicles', description: 'Postal delivery truck'),
      Symbol(label: 'Moving Truck', imagePath: 'emoji:🚚', category: 'Vehicles', description: 'Furniture moving truck'),
      Symbol(label: 'RV', imagePath: 'emoji:🚐', category: 'Vehicles', description: 'Recreational vehicle'),
      Symbol(label: 'Camper', imagePath: 'emoji:🚐', category: 'Vehicles', description: 'Camping trailer'),
      Symbol(label: 'Golf Cart', imagePath: 'emoji:🚗', category: 'Vehicles', description: 'Golf course cart'),
      Symbol(label: 'ATV', imagePath: 'emoji:🏍️', category: 'Vehicles', description: 'All-terrain vehicle'),
      Symbol(label: 'Snowmobile', imagePath: 'emoji:🛷', category: 'Vehicles', description: 'Snow vehicle'),
      Symbol(label: 'Jet Ski', imagePath: 'emoji:🚤', category: 'Vehicles', description: 'Water motorcycle'),
      Symbol(label: 'Kayak', imagePath: 'emoji:🛶', category: 'Vehicles', description: 'Single-person boat'),
      Symbol(label: 'Canoe', imagePath: 'emoji:🛶', category: 'Vehicles', description: 'Paddle boat'),
      Symbol(label: 'Raft', imagePath: 'emoji:🛟', category: 'Vehicles', description: 'Floating platform'),
      Symbol(label: 'Cruise Ship', imagePath: 'emoji:🛳️', category: 'Vehicles', description: 'Passenger cruise ship'),
      Symbol(label: 'Ferry', imagePath: 'emoji:⛴️', category: 'Vehicles', description: 'Car ferry boat'),
      Symbol(label: 'Speedboat', imagePath: 'emoji:🚤', category: 'Vehicles', description: 'Fast motorboat'),
      Symbol(label: 'Yacht', imagePath: 'emoji:🛥️', category: 'Vehicles', description: 'Luxury boat'),
      Symbol(label: 'Fighter Jet', imagePath: 'emoji:✈️', category: 'Vehicles', description: 'Military airplane'),

      // Emotions - 50+ feeling expressions  
      Symbol(label: 'Happy', imagePath: 'emoji:😊', category: 'Emotions', description: 'Feeling joyful'),
      Symbol(label: 'Sad', imagePath: 'emoji:😢', category: 'Emotions', description: 'Feeling down'),
      Symbol(label: 'Angry', imagePath: 'emoji:😠', category: 'Emotions', description: 'Feeling mad'),
      Symbol(label: 'Excited', imagePath: 'emoji:🤩', category: 'Emotions', description: 'Feeling thrilled'),
      Symbol(label: 'Scared', imagePath: 'emoji:😨', category: 'Emotions', description: 'Feeling afraid'),
      Symbol(label: 'Surprised', imagePath: 'emoji:😯', category: 'Emotions', description: 'Feeling shocked'),
      Symbol(label: 'Confused', imagePath: 'emoji:😕', category: 'Emotions', description: 'Feeling puzzled'),
      Symbol(label: 'Tired', imagePath: 'emoji:😴', category: 'Emotions', description: 'Feeling sleepy'),
      Symbol(label: 'Sick', imagePath: 'emoji:🤒', category: 'Emotions', description: 'Feeling unwell'),
      Symbol(label: 'Proud', imagePath: 'emoji:😌', category: 'Emotions', description: 'Feeling accomplished'),
      Symbol(label: 'Embarrassed', imagePath: 'emoji:😳', category: 'Emotions', description: 'Feeling shy'),
      Symbol(label: 'Worried', imagePath: 'emoji:😟', category: 'Emotions', description: 'Feeling anxious'),
      Symbol(label: 'Calm', imagePath: 'emoji:😌', category: 'Emotions', description: 'Feeling peaceful'),
      Symbol(label: 'Frustrated', imagePath: 'emoji:😤', category: 'Emotions', description: 'Feeling annoyed'),
      Symbol(label: 'Disappointed', imagePath: 'emoji:😞', category: 'Emotions', description: 'Feeling let down'),
      Symbol(label: 'Grateful', imagePath: 'emoji:🙏', category: 'Emotions', description: 'Feeling thankful'),
      Symbol(label: 'Lonely', imagePath: 'emoji:😔', category: 'Emotions', description: 'Feeling alone'),
      Symbol(label: 'Nervous', imagePath: 'emoji:😰', category: 'Emotions', description: 'Feeling uneasy'),
      Symbol(label: 'Relaxed', imagePath: 'emoji:😊', category: 'Emotions', description: 'Feeling at ease'),
      Symbol(label: 'Curious', imagePath: 'emoji:🤔', category: 'Emotions', description: 'Feeling interested'),
      Symbol(label: 'Bored', imagePath: 'emoji:😑', category: 'Emotions', description: 'Feeling uninterested'),
      Symbol(label: 'Hopeful', imagePath: 'emoji:🤞', category: 'Emotions', description: 'Feeling optimistic'),
      Symbol(label: 'Jealous', imagePath: 'emoji:😒', category: 'Emotions', description: 'Feeling envious'),
      Symbol(label: 'Guilty', imagePath: 'emoji:😔', category: 'Emotions', description: 'Feeling bad'),
      Symbol(label: 'Shocked', imagePath: 'emoji:😱', category: 'Emotions', description: 'Feeling stunned'),
      Symbol(label: 'Disgusted', imagePath: 'emoji:🤢', category: 'Emotions', description: 'Feeling grossed out'),
      Symbol(label: 'Amazed', imagePath: 'emoji:🤯', category: 'Emotions', description: 'Feeling wonder'),
      Symbol(label: 'Peaceful', imagePath: 'emoji:☺️', category: 'Emotions', description: 'Feeling serene'),
      Symbol(label: 'Energetic', imagePath: 'emoji:⚡', category: 'Emotions', description: 'Feeling active'),
      Symbol(label: 'Sleepy', imagePath: 'emoji:💤', category: 'Emotions', description: 'Feeling drowsy'),
      Symbol(label: 'Giggly', imagePath: 'emoji:🤭', category: 'Emotions', description: 'Feeling silly'),
      Symbol(label: 'Cranky', imagePath: 'emoji:😾', category: 'Emotions', description: 'Feeling grumpy'),
      Symbol(label: 'Loving', imagePath: 'emoji:🥰', category: 'Emotions', description: 'Feeling affectionate'),
      Symbol(label: 'Silly', imagePath: 'emoji:🤪', category: 'Emotions', description: 'Feeling goofy'),
      Symbol(label: 'Thoughtful', imagePath: 'emoji:🧐', category: 'Emotions', description: 'Feeling contemplative'),
      Symbol(label: 'Cheerful', imagePath: 'emoji:😄', category: 'Emotions', description: 'Feeling bright'),
      Symbol(label: 'Gloomy', imagePath: 'emoji:☁️', category: 'Emotions', description: 'Feeling dark'),
      Symbol(label: 'Overwhelmed', imagePath: 'emoji:🤯', category: 'Emotions', description: 'Feeling too much'),
      Symbol(label: 'Content', imagePath: 'emoji:😌', category: 'Emotions', description: 'Feeling satisfied'),
      Symbol(label: 'Moody', imagePath: 'emoji:😒', category: 'Emotions', description: 'Feeling changeable'),
      Symbol(label: 'Playful', imagePath: 'emoji:😜', category: 'Emotions', description: 'Feeling fun'),
      Symbol(label: 'Serious', imagePath: 'emoji:😐', category: 'Emotions', description: 'Feeling focused'),
      Symbol(label: 'Brave', imagePath: 'emoji:💪', category: 'Emotions', description: 'Feeling courageous'),
      Symbol(label: 'Shy', imagePath: 'emoji:🙈', category: 'Emotions', description: 'Feeling timid'),
      Symbol(label: 'Confident', imagePath: 'emoji:😎', category: 'Emotions', description: 'Feeling sure'),
      Symbol(label: 'Insecure', imagePath: 'emoji:😟', category: 'Emotions', description: 'Feeling uncertain'),
      Symbol(label: 'Motivated', imagePath: 'emoji:🔥', category: 'Emotions', description: 'Feeling driven'),
      Symbol(label: 'Lazy', imagePath: 'emoji:😪', category: 'Emotions', description: 'Feeling unmotivated'),
      Symbol(label: 'Impressed', imagePath: 'emoji:😲', category: 'Emotions', description: 'Feeling awed'),
      Symbol(label: 'Unimpressed', imagePath: 'emoji:🙄', category: 'Emotions', description: 'Feeling meh'),

      // Actions - 50+ common verbs and activities
      Symbol(label: 'Walk', imagePath: 'emoji:🚶', category: 'Actions', description: 'Moving on foot'),
      Symbol(label: 'Run', imagePath: 'emoji:🏃', category: 'Actions', description: 'Moving fast'),
      Symbol(label: 'Jump', imagePath: 'emoji:🤸', category: 'Actions', description: 'Leap up high'),
      Symbol(label: 'Sit', imagePath: 'emoji:🪑', category: 'Actions', description: 'Rest on chair'),
      Symbol(label: 'Stand', imagePath: 'emoji:🧍', category: 'Actions', description: 'Be upright'),
      Symbol(label: 'Sleep', imagePath: 'emoji:😴', category: 'Actions', description: 'Rest and dream'),
      Symbol(label: 'Eat', imagePath: 'emoji:🍽️', category: 'Actions', description: 'Consume food'),
      Symbol(label: 'Drink', imagePath: 'emoji:🥤', category: 'Actions', description: 'Consume liquid'),
      Symbol(label: 'Play', imagePath: 'emoji:🎮', category: 'Actions', description: 'Have fun'),
      Symbol(label: 'Read', imagePath: 'emoji:📖', category: 'Actions', description: 'Look at words'),
      Symbol(label: 'Write', imagePath: 'emoji:✏️', category: 'Actions', description: 'Make words'),
      Symbol(label: 'Draw', imagePath: 'emoji:🎨', category: 'Actions', description: 'Make pictures'),
      Symbol(label: 'Sing', imagePath: 'emoji:🎤', category: 'Actions', description: 'Make music'),
      Symbol(label: 'Dance', imagePath: 'emoji:💃', category: 'Actions', description: 'Move to music'),
      Symbol(label: 'Watch', imagePath: 'emoji:👀', category: 'Actions', description: 'Look at something'),
      Symbol(label: 'Listen', imagePath: 'emoji:👂', category: 'Actions', description: 'Hear sounds'),
      Symbol(label: 'Talk', imagePath: 'emoji:💬', category: 'Actions', description: 'Speak words'),
      Symbol(label: 'Laugh', imagePath: 'emoji:😂', category: 'Actions', description: 'Make happy sounds'),
      Symbol(label: 'Cry', imagePath: 'emoji:😭', category: 'Actions', description: 'Shed tears'),
      Symbol(label: 'Hug', imagePath: 'emoji:🤗', category: 'Actions', description: 'Embrace someone'),
      Symbol(label: 'Kiss', imagePath: 'emoji:😘', category: 'Actions', description: 'Show affection'),
      Symbol(label: 'Wave', imagePath: 'emoji:👋', category: 'Actions', description: 'Greet with hand'),
      Symbol(label: 'Clap', imagePath: 'emoji:👏', category: 'Actions', description: 'Hit hands together'),
      Symbol(label: 'Point', imagePath: 'emoji:👉', category: 'Actions', description: 'Show direction'),
      Symbol(label: 'Think', imagePath: 'emoji:🤔', category: 'Actions', description: 'Use mind'),
      Symbol(label: 'Remember', imagePath: 'emoji:💭', category: 'Actions', description: 'Recall information'),
      Symbol(label: 'Forget', imagePath: 'emoji:🤷', category: 'Actions', description: 'Lose memory'),
      Symbol(label: 'Learn', imagePath: 'emoji:🎓', category: 'Actions', description: 'Gain knowledge'),
      Symbol(label: 'Teach', imagePath: 'emoji:👨‍🏫', category: 'Actions', description: 'Share knowledge'),
      Symbol(label: 'Help', imagePath: 'emoji:🤝', category: 'Actions', description: 'Assist others'),
      Symbol(label: 'Clean', imagePath: 'emoji:🧽', category: 'Actions', description: 'Make tidy'),
      Symbol(label: 'Cook', imagePath: 'emoji:👨‍🍳', category: 'Actions', description: 'Prepare food'),
      Symbol(label: 'Build', imagePath: 'emoji:🔨', category: 'Actions', description: 'Construct things'),
      Symbol(label: 'Fix', imagePath: 'emoji:🔧', category: 'Actions', description: 'Repair broken'),
      Symbol(label: 'Break', imagePath: 'emoji:💥', category: 'Actions', description: 'Damage object'),
      Symbol(label: 'Open', imagePath: 'emoji:🔓', category: 'Actions', description: 'Make accessible'),
      Symbol(label: 'Close', imagePath: 'emoji:🔒', category: 'Actions', description: 'Shut tight'),
      Symbol(label: 'Push', imagePath: 'emoji:👐', category: 'Actions', description: 'Move away'),
      Symbol(label: 'Pull', imagePath: 'emoji:👊', category: 'Actions', description: 'Move toward'),
      Symbol(label: 'Throw', imagePath: 'emoji:🏈', category: 'Actions', description: 'Toss object'),
      Symbol(label: 'Catch', imagePath: 'emoji:🤲', category: 'Actions', description: 'Grab object'),
      Symbol(label: 'Give', imagePath: 'emoji:🎁', category: 'Actions', description: 'Offer something'),
      Symbol(label: 'Take', imagePath: 'emoji:✋', category: 'Actions', description: 'Receive something'),
      Symbol(label: 'Share', imagePath: 'emoji:🤝', category: 'Actions', description: 'Split equally'),
      Symbol(label: 'Hide', imagePath: 'emoji:🙈', category: 'Actions', description: 'Stay unseen'),
      Symbol(label: 'Find', imagePath: 'emoji:🔍', category: 'Actions', description: 'Locate object'),
      Symbol(label: 'Lose', imagePath: 'emoji:🤷', category: 'Actions', description: 'Misplace object'),
      Symbol(label: 'Win', imagePath: 'emoji:🏆', category: 'Actions', description: 'Come first'),
      Symbol(label: 'Exercise', imagePath: 'emoji:💪', category: 'Actions', description: 'Work out'),
      Symbol(label: 'Rest', imagePath: 'emoji:😌', category: 'Actions', description: 'Take break'),

      // Family - 50+ relationship terms
      Symbol(label: 'Mom', imagePath: 'emoji:👩', category: 'Family', description: 'Mother figure'),
      Symbol(label: 'Dad', imagePath: 'emoji:👨', category: 'Family', description: 'Father figure'),
      Symbol(label: 'Sister', imagePath: 'emoji:👧', category: 'Family', description: 'Female sibling'),
      Symbol(label: 'Brother', imagePath: 'emoji:👦', category: 'Family', description: 'Male sibling'),
      Symbol(label: 'Grandma', imagePath: 'emoji:👵', category: 'Family', description: 'Grandmother'),
      Symbol(label: 'Grandpa', imagePath: 'emoji:👴', category: 'Family', description: 'Grandfather'),
      Symbol(label: 'Baby', imagePath: 'emoji:👶', category: 'Family', description: 'Young child'),
      Symbol(label: 'Child', imagePath: 'emoji:🧒', category: 'Family', description: 'Young person'),
      Symbol(label: 'Adult', imagePath: 'emoji:🧑', category: 'Family', description: 'Grown person'),
      Symbol(label: 'Family', imagePath: 'emoji:👨‍👩‍👧‍👦', category: 'Family', description: 'Related people'),
      Symbol(label: 'Aunt', imagePath: 'emoji:👩', category: 'Family', description: 'Parents sister'),
      Symbol(label: 'Uncle', imagePath: 'emoji:👨', category: 'Family', description: 'Parents brother'),
      Symbol(label: 'Cousin', imagePath: 'emoji:👫', category: 'Family', description: 'Related child'),
      Symbol(label: 'Friend', imagePath: 'emoji:👫', category: 'Family', description: 'Close companion'),
      Symbol(label: 'Teacher', imagePath: 'emoji:👨‍🏫', category: 'Family', description: 'Education provider'),
      Symbol(label: 'Doctor', imagePath: 'emoji:👨‍⚕️', category: 'Family', description: 'Medical helper'),
      Symbol(label: 'Nurse', imagePath: 'emoji:👩‍⚕️', category: 'Family', description: 'Medical assistant'),
      Symbol(label: 'Police', imagePath: 'emoji:👮', category: 'Family', description: 'Safety officer'),
      Symbol(label: 'Firefighter', imagePath: 'emoji:👨‍🚒', category: 'Family', description: 'Fire safety'),
      Symbol(label: 'Mailman', imagePath: 'emoji:👨‍💼', category: 'Family', description: 'Letter deliverer'),
      Symbol(label: 'Cashier', imagePath: 'emoji:👩‍💼', category: 'Family', description: 'Store worker'),
      Symbol(label: 'Cook', imagePath: 'emoji:👨‍🍳', category: 'Family', description: 'Food preparer'),
      Symbol(label: 'Mechanic', imagePath: 'emoji:👨‍🔧', category: 'Family', description: 'Car fixer'),
      Symbol(label: 'Farmer', imagePath: 'emoji:👨‍🌾', category: 'Family', description: 'Food grower'),
      Symbol(label: 'Artist', imagePath: 'emoji:👨‍🎨', category: 'Family', description: 'Creative maker'),
      Symbol(label: 'Musician', imagePath: 'emoji:👨‍🎤', category: 'Family', description: 'Music maker'),
      Symbol(label: 'Athlete', imagePath: 'emoji:🏃‍♂️', category: 'Family', description: 'Sports player'),
      Symbol(label: 'Student', imagePath: 'emoji:👨‍🎓', category: 'Family', description: 'Learning person'),
      Symbol(label: 'Pilot', imagePath: 'emoji:👨‍✈️', category: 'Family', description: 'Airplane driver'),
      Symbol(label: 'Dentist', imagePath: 'emoji:🦷', category: 'Family', description: 'Tooth doctor'),
      Symbol(label: 'Veterinarian', imagePath: 'emoji:👨‍⚕️', category: 'Family', description: 'Animal doctor'),
      Symbol(label: 'Librarian', imagePath: 'emoji:👩‍💼', category: 'Family', description: 'Book helper'),
      Symbol(label: 'Builder', imagePath: 'emoji:👷', category: 'Family', description: 'House maker'),
      Symbol(label: 'Janitor', imagePath: 'emoji:🧹', category: 'Family', description: 'Cleaning person'),
      Symbol(label: 'Guard', imagePath: 'emoji:💂', category: 'Family', description: 'Security person'),
      Symbol(label: 'Driver', imagePath: 'emoji:👨‍💼', category: 'Family', description: 'Vehicle operator'),
      Symbol(label: 'Scientist', imagePath: 'emoji:👨‍🔬', category: 'Family', description: 'Research person'),
      Symbol(label: 'Lawyer', imagePath: 'emoji:👨‍💼', category: 'Family', description: 'Law helper'),
      Symbol(label: 'Judge', imagePath: 'emoji:👩‍⚖️', category: 'Family', description: 'Decision maker'),
      Symbol(label: 'President', imagePath: 'emoji:🏛️', category: 'Family', description: 'Country leader'),
      Symbol(label: 'Manager', imagePath: 'emoji:👩‍💼', category: 'Family', description: 'Work boss'),
      Symbol(label: 'Secretary', imagePath: 'emoji:👩‍💼', category: 'Family', description: 'Office helper'),
      Symbol(label: 'Photographer', imagePath: 'emoji:📸', category: 'Family', description: 'Picture taker'),
      Symbol(label: 'Reporter', imagePath: 'emoji:📰', category: 'Family', description: 'News writer'),
      Symbol(label: 'Actor', imagePath: 'emoji:🎭', category: 'Family', description: 'Movie player'),
      Symbol(label: 'Singer', imagePath: 'emoji:🎤', category: 'Family', description: 'Song maker'),
      Symbol(label: 'Dancer', imagePath: 'emoji:💃', category: 'Family', description: 'Movement artist'),
      Symbol(label: 'Neighbor', imagePath: 'emoji:🏠', category: 'Family', description: 'Nearby person'),
      Symbol(label: 'Stranger', imagePath: 'emoji:❓', category: 'Family', description: 'Unknown person'),
      Symbol(label: 'Pet', imagePath: 'emoji:🐕', category: 'Family', description: 'Animal friend'),

      // Basic Needs - 50+ essential items and activities
      Symbol(label: 'Bathroom', imagePath: 'emoji:🚽', category: 'Basic Needs', description: 'Toilet room'),
      Symbol(label: 'Toilet', imagePath: 'emoji:🚽', category: 'Basic Needs', description: 'Waste disposal'),
      Symbol(label: 'Shower', imagePath: 'emoji:🚿', category: 'Basic Needs', description: 'Water cleaning'),
      Symbol(label: 'Bath', imagePath: 'emoji:🛁', category: 'Basic Needs', description: 'Tub washing'),
      Symbol(label: 'Brush Teeth', imagePath: 'emoji:🦷', category: 'Basic Needs', description: 'Clean teeth'),
      Symbol(label: 'Wash Hands', imagePath: 'emoji:🧼', category: 'Basic Needs', description: 'Clean hands'),
      Symbol(label: 'Bed', imagePath: 'emoji:🛏️', category: 'Basic Needs', description: 'Sleep place'),
      Symbol(label: 'Pillow', imagePath: 'emoji:🧘‍♀️', category: 'Basic Needs', description: 'Head rest'),
      Symbol(label: 'Blanket', imagePath: 'emoji:🧺', category: 'Basic Needs', description: 'Warm cover'),
      Symbol(label: 'Clothes', imagePath: 'emoji:👕', category: 'Basic Needs', description: 'Body covering'),
      Symbol(label: 'Shoes', imagePath: 'emoji:👟', category: 'Basic Needs', description: 'Foot covering'),
      Symbol(label: 'Coat', imagePath: 'emoji:🧥', category: 'Basic Needs', description: 'Warm jacket'),
      Symbol(label: 'Hat', imagePath: 'emoji:👒', category: 'Basic Needs', description: 'Head covering'),
      Symbol(label: 'Glasses', imagePath: 'emoji:👓', category: 'Basic Needs', description: 'Eye help'),
      Symbol(label: 'Medicine', imagePath: 'emoji:💊', category: 'Basic Needs', description: 'Health pills'),
      Symbol(label: 'Band-Aid', imagePath: 'emoji:🩹', category: 'Basic Needs', description: 'Cut cover'),
      Symbol(label: 'Thermometer', imagePath: 'emoji:🌡️', category: 'Basic Needs', description: 'Temperature checker'),
      Symbol(label: 'Tissue', imagePath: 'emoji:🧻', category: 'Basic Needs', description: 'Nose cleaner'),
      Symbol(label: 'Soap', imagePath: 'emoji:🧼', category: 'Basic Needs', description: 'Cleaning bar'),
      Symbol(label: 'Shampoo', imagePath: 'emoji:🧴', category: 'Basic Needs', description: 'Hair cleaner'),
      Symbol(label: 'Towel', imagePath: 'emoji:🤧', category: 'Basic Needs', description: 'Drying cloth'),
      Symbol(label: 'Toothbrush', imagePath: 'emoji:🦷', category: 'Basic Needs', description: 'Tooth cleaner'),
      Symbol(label: 'Toothpaste', imagePath: 'emoji:🦷', category: 'Basic Needs', description: 'Tooth soap'),
      Symbol(label: 'Comb', imagePath: 'emoji:💇', category: 'Basic Needs', description: 'Hair organizer'),
      Symbol(label: 'Mirror', imagePath: 'emoji:🪞', category: 'Basic Needs', description: 'Reflection tool'),
      Symbol(label: 'Light', imagePath: 'emoji:💡', category: 'Basic Needs', description: 'Brightness source'),
      Symbol(label: 'Key', imagePath: 'emoji:🔑', category: 'Basic Needs', description: 'Door opener'),
      Symbol(label: 'Phone', imagePath: 'emoji:📱', category: 'Basic Needs', description: 'Communication device'),
      Symbol(label: 'Money', imagePath: 'emoji:💰', category: 'Basic Needs', description: 'Payment method'),
      Symbol(label: 'Wallet', imagePath: 'emoji:👛', category: 'Basic Needs', description: 'Money holder'),
      Symbol(label: 'Bag', imagePath: 'emoji:👜', category: 'Basic Needs', description: 'Item carrier'),
      Symbol(label: 'Backpack', imagePath: 'emoji:🎒', category: 'Basic Needs', description: 'School bag'),
      Symbol(label: 'Umbrella', imagePath: 'emoji:☂️', category: 'Basic Needs', description: 'Rain protector'),
      Symbol(label: 'Sunglasses', imagePath: 'emoji:🕶️', category: 'Basic Needs', description: 'Sun protector'),
      Symbol(label: 'Watch', imagePath: 'emoji:⌚', category: 'Basic Needs', description: 'Time keeper'),
      Symbol(label: 'Calendar', imagePath: 'emoji:📅', category: 'Basic Needs', description: 'Date tracker'),
      Symbol(label: 'Clock', imagePath: 'emoji:🕐', category: 'Basic Needs', description: 'Time display'),
      Symbol(label: 'Alarm', imagePath: 'emoji:⏰', category: 'Basic Needs', description: 'Wake-up sound'),
      Symbol(label: 'Computer', imagePath: 'emoji:💻', category: 'Basic Needs', description: 'Work machine'),
      Symbol(label: 'Tablet', imagePath: 'emoji:📱', category: 'Basic Needs', description: 'Touch screen'),
      Symbol(label: 'TV', imagePath: 'emoji:📺', category: 'Basic Needs', description: 'Video display'),
      Symbol(label: 'Remote', imagePath: 'emoji:📱', category: 'Basic Needs', description: 'TV controller'),
      Symbol(label: 'Radio', imagePath: 'emoji:📻', category: 'Basic Needs', description: 'Sound player'),
      Symbol(label: 'Camera', imagePath: 'emoji:📸', category: 'Basic Needs', description: 'Picture maker'),
      Symbol(label: 'Book', imagePath: 'emoji:📖', category: 'Basic Needs', description: 'Reading material'),
      Symbol(label: 'Pen', imagePath: 'emoji:🖊️', category: 'Basic Needs', description: 'Writing tool'),
      Symbol(label: 'Paper', imagePath: 'emoji:📄', category: 'Basic Needs', description: 'Writing surface'),
      Symbol(label: 'Scissors', imagePath: 'emoji:✂️', category: 'Basic Needs', description: 'Cutting tool'),
      Symbol(label: 'Tape', imagePath: 'emoji:📦', category: 'Basic Needs', description: 'Sticky strip'),
      Symbol(label: 'Glue', imagePath: 'emoji:📦', category: 'Basic Needs', description: 'Sticky liquid'),
    ];
  }

  static Map<String, String> getCategoryEmojis() {
    return {
      'Food & Drinks': '🍎',
      'Vehicles': '🚗',
      'Emotions': '😊',
      'Actions': '🏃',
      'Family': '👨‍👩‍👧‍👦',
      'Basic Needs': '🙏',
    };
  }
}